### ISSUE TITLE
AssertionError: can only join a child process

### ISSUE THREAD

**Issue by eulerhackz** [zealotjin/wsgi_app#3]
Found your article 
```
☺  python app.py                                                              main ✗
Starting background thread
[2023-12-07 18:00:32 +0530] [21217] [INFO] Starting gunicorn 21.2.0
[2023-12-07 18:00:32 +0530] [21217] [INFO] Listening at: http://0.0.0.0:8080 (21217)
[2023-12-07 18:00:32 +0530] [21217] [INFO] Using worker: sync
[2023-12-07 18:00:32 +0530] [21220] [INFO] Booting worker with pid: 21220
[2023-12-07 18:00:32 +0530] [21221] [INFO] Booting worker with pid: 21221
[2023-12-07 18:00:32 +0530] [21222] [INFO] Booting worker with pid: 21222
[2023-12-07 18:00:32 +0530] [21223] [INFO] Booting worker with pid: 21223
[2023-12-07 18:00:32 +0530] [21224] [INFO] Booting worker with pid: 21224
[2023-12-07 18:00:37 +0530] [21217] [INFO] Handling signal: hup
[2023-12-07 18:00:37 +0530] [21217] [INFO] Hang up: Master
[2023-12-07 18:00:37 +0530] [21417] [INFO] Booting worker with pid: 21417
[2023-12-07 18:00:37 +0530] [21418] [INFO] Booting worker with pid: 21418
[2023-12-07 18:00:37 +0530] [21420] [INFO] Booting worker with pid: 21420
[2023-12-07 18:00:37 +0530] [21419] [INFO] Booting worker with pid: 21419
[2023-12-07 18:00:37 +0530] [21222] [INFO] Worker exiting (pid: 21222)
[2023-12-07 18:00:37 +0530] [21221] [INFO] Worker exiting (pid: 21221)
[2023-12-07 18:00:37 +0530] [21223] [INFO] Worker exiting (pid: 21223)
[2023-12-07 18:00:37 +0530] [21421] [INFO] Booting worker with pid: 21421
[2023-12-07 18:00:37 +0530] [21224] [INFO] Worker exiting (pid: 21224)
[2023-12-07 18:00:37 +0530] [21220] [INFO] Worker exiting (pid: 21220)
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
    p.join()
    p.join()
    p.join()
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
    p.join()
    p.join()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
    assert self._parent_pid == os.getpid(), 'can only join a child process'
    assert self._parent_pid == os.getpid(), 'can only join a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
    assert self._parent_pid == os.getpid(), 'can only join a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
    assert self._parent_pid == os.getpid(), 'can only join a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
^C[2023-12-07 18:00:39 +0530] [21217] [INFO] Handling signal: int
[2023-12-07 18:00:39 +0530] [21417] [INFO] Worker exiting (pid: 21417)
[2023-12-07 18:00:39 +0530] [21421] [INFO] Worker exiting (pid: 21421)
[2023-12-07 18:00:39 +0530] [21419] [INFO] Worker exiting (pid: 21419)
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
    p.join()
    p.join()
[2023-12-07 18:00:39 +0530] [21418] [INFO] Worker exiting (pid: 21418)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
    assert self._parent_pid == os.getpid(), 'can only join a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
AssertionError: can only join a child process
    p.join()
[2023-12-07 18:00:39 +0530] [21420] [INFO] Worker exiting (pid: 21420)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
    assert self._parent_pid == os.getpid(), 'can only join a child process'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
    p.join()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
Exception ignored in atexit callback: <function _exit_function at 0x1066c7240>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 147, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only join a child process
```

**Comment by eulerhackz** [comment]
as a wayaround I did this,


```python
import logging
from werkzeug.middleware.proxy_fix import ProxyFix
from gevent.pywsgi import WSGIServer
from settings import settings
from my_app import app

def production(app: Flask):
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)
    logging.info("Proxy configuration successful.")
    http_server = WSGIServer((settings.host, settings.port), application=app)
    http_server.serve_forever()
```
